#!/bin/bash

[[ "$EUID" -eq "0" ]] || { sudo -p "Please enter your password to continue: " "$0" "$@"; exit $?; }

set -e

rm -f ubuntu.iso

source fetch_build.conf
wget ubuntu.iso "$DOWNLOAD_ISO"; sudo chmod +x ./build/build.sh ./build/switch.sh ./build/minimal.sh
sudo make build.iso
